{-# LANGUAGE OverloadedStrings #-}

module Imako.UI.Scripts (
  appScripts,
)
where

import Lucid

-- | All client-side scripts for the application
appScripts :: Html ()
appScripts = do
  script_ [] $
    unlines
      [ "const STORAGE_KEY_FOLDERS = 'imako-folder-states';"
      , "const STORAGE_KEY_FILTERS = 'imako-filter-states';"
      , ""
      , "// --- Folder State Logic ---"
      , ""
      , "function saveFolderState(path, isOpen) {"
      , "  const states = JSON.parse(localStorage.getItem(STORAGE_KEY_FOLDERS) || '{}');"
      , "  states[path] = isOpen;"
      , "  localStorage.setItem(STORAGE_KEY_FOLDERS, JSON.stringify(states));"
      , "}"
      , ""
      , "function loadFolderStates() {"
      , "  return JSON.parse(localStorage.getItem(STORAGE_KEY_FOLDERS) || '{}');"
      , "}"
      , ""
      , "function restoreFolderListeners() {"
      , "  const states = loadFolderStates();"
      , "  "
      , "  // Restore saved states for folders"
      , "  document.querySelectorAll('details[data-folder-path]').forEach(details => {"
      , "    const path = details.getAttribute('data-folder-path');"
      , "    if (path in states) {"
      , "      details.open = states[path];"
      , "    }"
      , "    "
      , "    // Remove old listeners to avoid duplicates"
      , "    details.replaceWith(details.cloneNode(true));"
      , "  });"
      , "  "
      , "  // Re-query after replacing nodes and attach listeners"
      , "  document.querySelectorAll('details[data-folder-path]').forEach(details => {"
      , "    details.addEventListener('toggle', () => {"
      , "      const path = details.getAttribute('data-folder-path');"
      , "      saveFolderState(path, details.open);"
      , "    });"
      , "  });"
      , "}"
      , ""
      , "// --- Filter State Logic ---"
      , ""
      , "function saveFilterState(filterName, isActive) {"
      , "  const states = JSON.parse(localStorage.getItem(STORAGE_KEY_FILTERS) || '{}');"
      , "  states[filterName] = isActive;"
      , "  localStorage.setItem(STORAGE_KEY_FILTERS, JSON.stringify(states));"
      , "}"
      , ""
      , "function loadFilterStates() {"
      , "  return JSON.parse(localStorage.getItem(STORAGE_KEY_FILTERS) || '{}');"
      , "}"
      , ""
      , "function toggleFutureTasks() {"
      , "  const container = document.getElementById('task-content');"
      , "  const btn = document.getElementById('future-tasks-toggle');"
      , "  if (!container || !btn) return;"
      , "  "
      , "  const isShowing = container.classList.toggle('show-future');"
      , "  btn.setAttribute('aria-pressed', isShowing);"
      , "  saveFilterState('showFuture', isShowing);"
      , "}"
      , ""
      , "function restoreFilterState() {"
      , "  const states = loadFilterStates();"
      , "  const container = document.getElementById('task-content');"
      , "  const btn = document.getElementById('future-tasks-toggle');"
      , "  "
      , "  if (states.showFuture) {"
      , "    if (container) container.classList.add('show-future');"
      , "    if (btn) btn.setAttribute('aria-pressed', 'true');"
      , "  } else {"
      , "    if (container) container.classList.remove('show-future');"
      , "    if (btn) btn.setAttribute('aria-pressed', 'false');"
      , "  }"
      , "}"
      , ""
      , "// --- Initialization ---"
      , ""
      , "function initApp() {"
      , "  restoreFolderListeners();"
      , "  restoreFilterState();"
      , "}"
      , ""
      , "// Restore on initial page load"
      , "document.addEventListener('DOMContentLoaded', initApp);"
      , ""
      , "// Restore after htmx swaps content"
      , "document.addEventListener('htmx:afterSwap', (evt) => {"
      , "  // Only restore if the swapped content is relevant (e.g. task list update)"
      , "  // But for now, restoring everything is safe enough"
      , "  initApp();"
      , "});"
      ]
